Repository nvbach91/4IZ278-2022-2023-LS, pull requests merged in 2023-06, with the labels that each got.

#340 lasj06-sp
  www/lasj06/sp/controller/authorization.php
  www/lasj06/sp/controller/buy_controller.php
  www/lasj06/sp/controller/cart_controller.php
  www/lasj06/sp/controller/home_controller.php
  www/lasj06/sp/controller/product_controller.php
  www/lasj06/sp/controller/remove_controller.php
  www/lasj06/sp/controller/search_controller.php
  www/lasj06/sp/controller/signin_controller.php
  www/lasj06/sp/controller/signout_controller.php
  www/lasj06/sp/controller/signup_controller.php
  www/lasj06/sp/controller/user_controller.php
  www/lasj06/sp/controller/user_required.php
  www/lasj06/sp/css/style.css
  www/lasj06/sp/favicon.ico
  www/lasj06/sp/google/google.php
  www/lasj06/sp/img/logo.png
  www/lasj06/sp/index.php
  www/lasj06/sp/js/main.js
  www/lasj06/sp/model/cart.php
  www/lasj06/sp/model/db.php
  www/lasj06/sp/model/products.php
  www/lasj06/sp/model/users.php
  www/lasj06/sp/view/about.php
  www/lasj06/sp/view/add_product.php
  www/lasj06/sp/view/cart.php
  www/lasj06/sp/view/edit_product.php
  www/lasj06/sp/view/edit_user.php
  www/lasj06/sp/view/home.php
  www/lasj06/sp/view/incl/footer.php
  www/lasj06/sp/view/incl/header.php
  www/lasj06/sp/view/order.php
  www/lasj06/sp/view/product.php
  www/lasj06/sp/view/signin.php
  www/lasj06/sp/view/signup.php
  www/lasj06/sp/view/user.php
  www/lasj06/sp/view/user_desc.php
  www/lasj06/sp/view/users.php
Labels: pending, in progress

#330 smap01-sp
  www/smap01/sp/actions/add-to-cart.php
  www/smap01/sp/actions/delete-item.php
  www/smap01/sp/actions/place-order.php
  www/smap01/sp/actions/remove-from-cart.php
  www/smap01/sp/add-a-book.php
  www/smap01/sp/add-review.php
  www/smap01/sp/book-detail.php
  www/smap01/sp/cart.php
  www/smap01/sp/composer.json
  www/smap01/sp/composer.lock
  www/smap01/sp/config.php
  www/smap01/sp/database/Database.php
  www/smap01/sp/database/OrdersDB.php
  www/smap01/sp/database/ProductsDB.php
  www/smap01/sp/database/ReviewsDB.php
  www/smap01/sp/database/UsersDB.php
  www/smap01/sp/database/config.php
  www/smap01/sp/edit-item.php
  www/smap01/sp/facebook-login.php
  www/smap01/sp/fb-login-callback.php
  www/smap01/sp/fb-login-callback2.php
  www/smap01/sp/incl/footer.php
  www/smap01/sp/incl/header.php
  www/smap01/sp/index.php
  www/smap01/sp/login.php
  www/smap01/sp/logout.php
  www/smap01/sp/main.php
  www/smap01/sp/php-actions/add-review.php
  www/smap01/sp/php-actions/buy.php
  www/smap01/sp/php-actions/create-item.php
  www/smap01/sp/php-actions/delete-item.php
  www/smap01/sp/php-actions/edit-item.php
  www/smap01/sp/php-actions/edit-review.php
  www/smap01/sp/php-actions/facebook/config.php
  www/smap01/sp/php-actions/facebook/facebook-login.php
  www/smap01/sp/php-actions/facebook/fb-login-callback.php
  www/smap01/sp/php-actions/facebook/fb-login-callback2.php
  www/smap01/sp/php-actions/logout.php
  www/smap01/sp/php-actions/remove-item.php
  www/smap01/sp/profile.php
  www/smap01/sp/signup.php
  www/smap01/sp/styles/stylesheet.css
  www/smap01/sp/users.php
Labels: pending, in progress

#316 bukp00-sp
  www/bukp00/sp/assets/favicon/android-chrome-192x192.png
  www/bukp00/sp/assets/favicon/android-chrome-512x512.png
  www/bukp00/sp/assets/favicon/apple-touch-icon.png
  www/bukp00/sp/assets/favicon/favicon-16x16.png
  www/bukp00/sp/assets/favicon/favicon-32x32.png
  www/bukp00/sp/assets/favicon/favicon.ico
  www/bukp00/sp/assets/logo.png
  www/bukp00/sp/assets/site.webmanifest
  www/bukp00/sp/components/category-filter.php
  www/bukp00/sp/components/event-detail.php
  www/bukp00/sp/components/events-list.php
  www/bukp00/sp/components/footer.php
  www/bukp00/sp/components/header.php
  www/bukp00/sp/components/modals/add-feedback-modal.php
  www/bukp00/sp/components/modals/event-form-modal.php
  www/bukp00/sp/components/modals/sign-up-modal.php
  www/bukp00/sp/components/my-events.php
  www/bukp00/sp/components/my-tickets.php
  www/bukp00/sp/components/product-list.php
  www/bukp00/sp/composer.json
  www/bukp00/sp/composer.lock
  www/bukp00/sp/config.example.php
  www/bukp00/sp/css/main.css
  www/bukp00/sp/database/Database.php
  www/bukp00/sp/database/EventsDB.php
  www/bukp00/sp/database/FeedbacksDB.php
  www/bukp00/sp/database/ParticipationsDB.php
  www/bukp00/sp/database/UsersDB.php
  www/bukp00/sp/event.php
  www/bukp00/sp/handlers/email-handler.php
  www/bukp00/sp/handlers/event-handlers.php
  www/bukp00/sp/handlers/feedback-handlers.php
  www/bukp00/sp/handlers/participation-handlers.php
  www/bukp00/sp/index.php
  www/bukp00/sp/login-callback.php
  www/bukp00/sp/login.php
  www/bukp00/sp/logout-callback.php
  www/bukp00/sp/logout.php
  www/bukp00/sp/organiser.php
  www/bukp00/sp/participant.php
  www/bukp00/sp/profile.php
  www/bukp00/sp/utils.php
  www/bukp00/sp/zadani.md
Labels: invalid PR, pending, in progress

#325 trep01-sp
  www/trep01/sp/App.php
  www/trep01/sp/_old/ftp_upload.php
  www/trep01/sp/_old/index.php
  www/trep01/sp/index.php
  www/trep01/sp/model/AccessConnection.php
  www/trep01/sp/model/Database.php
  www/trep01/sp/model/FtpConection.php
  www/trep01/sp/model/databaseConfig.php
  www/trep01/sp/repository/AccessesRepository.php
  www/trep01/sp/repository/Repository.php
  www/trep01/sp/repository/UserAccessesRepository.php
  www/trep01/sp/repository/UsersRepository.php
  www/trep01/sp/www/action/user/login.php
  www/trep01/sp/www/action/user/register.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/access/delete.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/access/save.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/change.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/download.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/ftp/connect.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/ftp/deleteLocalFile.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/ftp/uploadFile.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/header.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/newConnect.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/user/delete.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/user/login.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/user/logout.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/user/register.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/userAccess/add.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/action/userAccess/list.php
  www/trep01/sp/www/domains/apiftpklient.patriktrejtnar.cz/email/send.php
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/index.html
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/js/client.js
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/js/sidebars.js
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/layout/footer.php
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/layout/head.php
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/layout/header.php
  www/trep01/sp/www/domains/ftpklient.patriktrejtnar.cz/sidebars.css
  www/trep01/sp/www/index.php
  www/trep01/sp/www/layout/footer.php
  www/trep01/sp/www/layout/head.php
  www/trep01/sp/www/layout/header.php
Labels: pass, pending, in progress

#342 vikd00-sp
  www/vikd00/sp/AdDatabase.php
  www/vikd00/sp/ChatDatabase.php
  www/vikd00/sp/Database.php
  www/vikd00/sp/SpotlightDatabase.php
  www/vikd00/sp/UserDatabase.php
  www/vikd00/sp/ad-create.php
  www/vikd00/sp/ad-delete.php
  www/vikd00/sp/ad-detail.php
  www/vikd00/sp/ad-details.php
  www/vikd00/sp/ad-edit.php
  www/vikd00/sp/admin-delete-user.php
  www/vikd00/sp/admin-edit-ads.php
  www/vikd00/sp/admin-edit-users.php
  www/vikd00/sp/ads.php
  www/vikd00/sp/auth.php
  www/vikd00/sp/chat.php
  www/vikd00/sp/config.php
  www/vikd00/sp/custom.css
  www/vikd00/sp/db/Database.php
  www/vikd00/sp/db/SpotlightDatabase.php
  www/vikd00/sp/db/config.php
  www/vikd00/sp/fb-login-callback.php
  www/vikd00/sp/fb-login.php
  www/vikd00/sp/fbconfig.php
  www/vikd00/sp/footer.php
  www/vikd00/sp/get-messages.php
  www/vikd00/sp/header.php
  www/vikd00/sp/includes/navbar.php
  www/vikd00/sp/includes/search-container.php
  www/vikd00/sp/includes/spotlight.php
  www/vikd00/sp/index.php
  www/vikd00/sp/login.php
  www/vikd00/sp/logo-large.php
  www/vikd00/sp/logout.php
  www/vikd00/sp/navbar.php
  www/vikd00/sp/profile-edit.php
  www/vikd00/sp/profile.php
  www/vikd00/sp/readme.md
  www/vikd00/sp/redrive_logo.png
  www/vikd00/sp/redrive_logo_text.png
  www/vikd00/sp/register.php
  www/vikd00/sp/search-form.php
  www/vikd00/sp/send-message.php
  www/vikd00/sp/spotlight.php
  www/vikd00/sp/styles.css
Labels: pass, pending, in progress

#311 kulm11-sp
  www/kulm11/sp/Database.php
  www/kulm11/sp/ItemsDatabase.php
  www/kulm11/sp/README.md
  www/kulm11/sp/UsersDatabase.php
  www/kulm11/sp/add.php
  www/kulm11/sp/admin.php
  www/kulm11/sp/assets/css/style.css
  www/kulm11/sp/assets/img/background.jpg
  www/kulm11/sp/assets/img/logo.png
  www/kulm11/sp/assets/js/main.js
  www/kulm11/sp/buy.php
  www/kulm11/sp/changeItemQuantity.php
  www/kulm11/sp/changeProfile.php
  www/kulm11/sp/checkout.php
  www/kulm11/sp/checks/addCheck.php
  www/kulm11/sp/checks/changeProfileCheck.php
  www/kulm11/sp/checks/editCheck.php
  www/kulm11/sp/checks/loginCheck.php
  www/kulm11/sp/checks/signupCheck.php
  www/kulm11/sp/composer.json
  www/kulm11/sp/composer.lock
  www/kulm11/sp/config.php
  www/kulm11/sp/createOrder.php
  www/kulm11/sp/database/CategoriesDatabase.php
  www/kulm11/sp/database/Database.php
  www/kulm11/sp/database/ItemsDatabase.php
  www/kulm11/sp/database/OrdersDatabase.php
  www/kulm11/sp/database/UsersDatabase.php
  www/kulm11/sp/edit.php
  www/kulm11/sp/fb-login-callback.php
  www/kulm11/sp/fb-login-callback2.php
  www/kulm11/sp/history.php
  www/kulm11/sp/includes/footer.php
  www/kulm11/sp/includes/logo.php
  www/kulm11/sp/index.php
  www/kulm11/sp/item.php
  www/kulm11/sp/login.php
  www/kulm11/sp/loginViaFacebook.php
  www/kulm11/sp/logout.php
  www/kulm11/sp/orderhistory.php
  www/kulm11/sp/product.php
  www/kulm11/sp/remove.php
  www/kulm11/sp/removeItemCart.php
  www/kulm11/sp/signup.php
Labels: pending, in progress

#323 staj20-sp
  www/staj20/sp/account/index.php
  www/staj20/sp/account/login.php
  www/staj20/sp/account/logout.php
  www/staj20/sp/account/orderdetail.php
  www/staj20/sp/account/signup.php
  www/staj20/sp/account/useraddress.php
  www/staj20/sp/account/userorders.php
  www/staj20/sp/administration/allorders.php
  www/staj20/sp/administration/index.php
  www/staj20/sp/administration/orderdetail.php
  www/staj20/sp/assets/config/db-access.php
  www/staj20/sp/assets/config/google.php
  www/staj20/sp/assets/config/smtp-config.php
  www/staj20/sp/assets/css/print.css
  www/staj20/sp/assets/css/style.css
  www/staj20/sp/assets/img/auta-min.jpg
  www/staj20/sp/assets/img/favicon.ico
  www/staj20/sp/assets/img/sklenmala-min.jpg
  www/staj20/sp/assets/img/sklenvelka-min.jpg
  www/staj20/sp/assets/img/sud-min.jpg
  www/staj20/sp/assets/img/vasa-min.jpg
  www/staj20/sp/assets/php/account.php
  www/staj20/sp/assets/php/address.php
  www/staj20/sp/assets/php/cart.php
  www/staj20/sp/assets/php/core.php
  www/staj20/sp/assets/php/database.php
  www/staj20/sp/assets/php/header.php
  www/staj20/sp/assets/php/item.php
  www/staj20/sp/assets/php/mailsend.php
  www/staj20/sp/assets/php/order.php
  www/staj20/sp/assets/php/product.php
  www/staj20/sp/assets/php/products.php
  www/staj20/sp/cart/confirm.php
  www/staj20/sp/cart/index.php
  www/staj20/sp/cart/orderaddress.php
  www/staj20/sp/cart/success.php
  www/staj20/sp/composer.json
  www/staj20/sp/composer.lock
  www/staj20/sp/index.php
  www/staj20/sp/neworder/index.php
  www/staj20/sp/sp-eshop.sql
  www/staj20/sp/store/allproducts.php
  www/staj20/sp/store/auta/index.php
  www/staj20/sp/store/index.php
  www/staj20/sp/store/producta.php
  www/staj20/sp/store/sklenmala/index.php
  www/staj20/sp/store/sklenvelka/index.php
  www/staj20/sp/store/sud/index.php
  www/staj20/sp/store/vasa/index.php
Labels: needs fixing, in progress, unfinished

#315 vejm04-sp
  www/vejm04/sp/account.php
  www/vejm04/sp/cart.php
  www/vejm04/sp/category.php
  www/vejm04/sp/checkout.php
  www/vejm04/sp/config.php
  www/vejm04/sp/editUser.php
  www/vejm04/sp/googleLogin.php
  www/vejm04/sp/header.php
  www/vejm04/sp/index.php
  www/vejm04/sp/login.php
  www/vejm04/sp/logout.php
  www/vejm04/sp/manageCategories.php
  www/vejm04/sp/manageOrders.php
  www/vejm04/sp/manageProducts.php
  www/vejm04/sp/manageUsers.php
  www/vejm04/sp/privacyPolicy.php
  www/vejm04/sp/productDetail.php
  www/vejm04/sp/registration.php
  www/vejm04/sp/removeFromCart.php
  www/vejm04/sp/sendOrder.php
  www/vejm04/sp/styles/account.css
  www/vejm04/sp/styles/cart.css
  www/vejm04/sp/styles/category.css
  www/vejm04/sp/styles/checkout.css
  www/vejm04/sp/styles/common.css
  www/vejm04/sp/styles/editUser.css
  www/vejm04/sp/styles/header.css
  www/vejm04/sp/styles/login.css
  www/vejm04/sp/styles/manage.css
  www/vejm04/sp/styles/product-detail.css
  www/vejm04/sp/styles/registration.css
  www/vejm04/sp/styles/thankYou.css
  www/vejm04/sp/thankYou.php
  www/vejm04/sp/updateCart.php
Labels: pending, in progress

#337 engt01-sp
  www/engt01/sp/.gitignore
  www/engt01/sp/.htaccess
  www/engt01/sp/actions/deleteBookAction.php
  www/engt01/sp/actions/editBookAction.php
  www/engt01/sp/actions/removeReservationAction.php
  www/engt01/sp/actions/reserveDetailAction.php
  www/engt01/sp/actions/reserveIndexAction.php
  www/engt01/sp/actions/userChangeAction.php
  www/engt01/sp/book-list.php
  www/engt01/sp/book-queue.php
  www/engt01/sp/branch.php
  www/engt01/sp/components/.htaccess
  www/engt01/sp/components/footer.php
  www/engt01/sp/components/header.php
  www/engt01/sp/composer.json
  www/engt01/sp/composer.lock
  www/engt01/sp/css/bootstrap.css
  www/engt01/sp/css/styles.css
  www/engt01/sp/db/BooksDatabase.php
  www/engt01/sp/db/CategoriesDatabase.php
  www/engt01/sp/db/Database.php
  www/engt01/sp/db/LoansDatabase.php
  www/engt01/sp/db/ReservationsDatabase.php
  www/engt01/sp/db/UserDatabase.php
  www/engt01/sp/detail.php
  www/engt01/sp/edit-book.php
  www/engt01/sp/fb-login-callback.php
  www/engt01/sp/index.php
  www/engt01/sp/login.php
  www/engt01/sp/logout.php
  www/engt01/sp/profile.php
  www/engt01/sp/register.php
  www/engt01/sp/tos-pp.php
Labels: in progress, unfinished

#299 adaa08-sp
  www/adaa08/sp/account.php
  www/adaa08/sp/add_product.php
  www/adaa08/sp/add_to_cart.php
  www/adaa08/sp/admin.php
  www/adaa08/sp/cancel_order.php
  www/adaa08/sp/cart.php
  www/adaa08/sp/change_role.php
  www/adaa08/sp/classes/Address.php
  www/adaa08/sp/classes/Admin.php
  www/adaa08/sp/classes/Cart.php
  www/adaa08/sp/classes/Category.php
  www/adaa08/sp/classes/Database.php
  www/adaa08/sp/classes/Order.php
  www/adaa08/sp/classes/Product.php
  www/adaa08/sp/classes/User.php
  www/adaa08/sp/delete_product.php
  www/adaa08/sp/delete_user.php
  www/adaa08/sp/edit_product.php
  www/adaa08/sp/email.php
  www/adaa08/sp/fb_callback.php
  www/adaa08/sp/fb_config.php
  www/adaa08/sp/fb_login.php
  www/adaa08/sp/fb_register.php
  www/adaa08/sp/footer.php
  www/adaa08/sp/header.php
  www/adaa08/sp/index.php
  www/adaa08/sp/insert_product.php
  www/adaa08/sp/js/product.js
  www/adaa08/sp/js/script.js
  www/adaa08/sp/login.php
  www/adaa08/sp/logout.php
  www/adaa08/sp/mark_as_completed.php
  www/adaa08/sp/meta.php
  www/adaa08/sp/order.php
  www/adaa08/sp/order_details.php
  www/adaa08/sp/order_success.php
  www/adaa08/sp/pictures/icon.svg
  www/adaa08/sp/pictures/kaniva.jpeg
  www/adaa08/sp/pictures/kitchenStore.webp
  www/adaa08/sp/pictures/mikrovlnka.jpeg
  www/adaa08/sp/pictures/mikrovlnka.jpg
  www/adaa08/sp/pictures/nozik.jpeg
  www/adaa08/sp/privacy_policy.php
  www/adaa08/sp/process_order.php
  www/adaa08/sp/product.php
  www/adaa08/sp/register.php
  www/adaa08/sp/remove_from_cart.php
  www/adaa08/sp/set_cookie.php
  www/adaa08/sp/styles/style.css
  www/adaa08/sp/terms_of_service.php
  www/adaa08/sp/update_product.php
  www/adaa08/sp/user_deleton.php
Labels: pending, in progress

#314 bigc00-sp
  www/bigc00/shop/404.php
  www/bigc00/shop/admin.php
  www/bigc00/shop/cart.php
  www/bigc00/shop/db.php
  www/bigc00/shop/functions.php
  www/bigc00/shop/index.php
  www/bigc00/shop/order.php
  www/bigc00/shop/single.php
  www/bigc00/shop/styles.css
  www/bigc00/sp/404.php
  www/bigc00/sp/Utils.php
  www/bigc00/sp/admin.php
  www/bigc00/sp/cart.php
  www/bigc00/sp/composer.json
  www/bigc00/sp/composer.lock
  www/bigc00/sp/database/AccountsDB.php
  www/bigc00/sp/database/Database.php
  www/bigc00/sp/database/DatabaseOperations.php
  www/bigc00/sp/database/TransactionsDB.php
  www/bigc00/sp/database/UsersDB.php
  www/bigc00/sp/database/config.php
  www/bigc00/sp/db.php
  www/bigc00/sp/fonts/Joyride W05 STD.ttf
  www/bigc00/sp/functions.php
  www/bigc00/sp/google-callback.php
  www/bigc00/sp/img/logo.png
  www/bigc00/sp/img/post-image.png
  www/bigc00/sp/imgs/1.jpg
  www/bigc00/sp/imgs/10.jpg
  www/bigc00/sp/imgs/11.jpg
  www/bigc00/sp/imgs/12.jpg
  www/bigc00/sp/imgs/22.jpg
  www/bigc00/sp/imgs/3.jpg
  www/bigc00/sp/imgs/4.jpg
  www/bigc00/sp/imgs/5.jpg
  www/bigc00/sp/imgs/6.jpg
  www/bigc00/sp/imgs/7.jpg
  www/bigc00/sp/imgs/8.jpg
  www/bigc00/sp/imgs/9.jpg
  www/bigc00/sp/includes/accounts.php
  www/bigc00/sp/includes/adminPanel.php
  www/bigc00/sp/includes/header.php
  www/bigc00/sp/includes/history.php
  www/bigc00/sp/includes/login.php
  www/bigc00/sp/includes/main.php
  www/bigc00/sp/includes/newAccount.php
  www/bigc00/sp/includes/newPayment.php
  www/bigc00/sp/includes/registration.php
  www/bigc00/sp/index.php
  www/bigc00/sp/login.php
  www/bigc00/sp/logout.php
  www/bigc00/sp/order.php
  www/bigc00/sp/pay.php
  www/bigc00/sp/profile.php
  www/bigc00/sp/registration.php
  www/bigc00/sp/sendingOrder.php
  www/bigc00/sp/single.php
  www/bigc00/sp/styles.css
  www/bigc00/sp/styles/styles.css
Labels: in progress, unfinished
