Repository nvbach91/4IZ278-2022-2023-LS, pull requests merged in 2023-04, with the labels that each got.

#196 smap01-cv05
  www/smap01/cv05/Database/ordersDB.db
  www/smap01/cv05/Database/productsDB.db
  www/smap01/cv05/Database/usersDB.db
  www/smap01/cv05/OrdersDB.php
  www/smap01/cv05/ProductsDB.php
  www/smap01/cv05/UsersDB.php
  www/smap01/cv05/css/styles.css
  www/smap01/cv05/database.php
  www/smap01/cv05/database/ordersDB.db
  www/smap01/cv05/database/productsDB.db
  www/smap01/cv05/database/usersDB.db
  www/smap01/cv05/databaseOperations.php
  www/smap01/cv05/includes/footer.php
  www/smap01/cv05/includes/header.php
  www/smap01/cv05/index.php
Labels: needs fixing

#199 mikd08-cv06
  www/mikd08/cv1/js.js
  www/mikd08/cv5/db.php
  www/mikd08/cv6/Categories.php
  www/mikd08/cv6/Database.php
  www/mikd08/cv6/Products.php
  www/mikd08/cv6/Slides.php
  www/mikd08/cv6/categoriesHTML.php
  www/mikd08/cv6/dbinfo.php
  www/mikd08/cv6/index.php
  www/mikd08/cv6/productsHTML.php
  www/mikd08/cv6/slidesHTML.php
  www/mikd08/cv6/style.css
Labels: pass, needs fixing

#200 vikd00-cv06
  www/vikd00/cv06/CategoriesDatabase.php
  www/vikd00/cv06/CategoryDisplay.php
  www/vikd00/cv06/Database.php
  www/vikd00/cv06/ProductDisplay.php
  www/vikd00/cv06/ProductsDatabase.php
  www/vikd00/cv06/SliderDisplay.php
  www/vikd00/cv06/SlidesDatabase.php
  www/vikd00/cv06/dbconfig.php
  www/vikd00/cv06/index.php
  www/vikd00/cv06/styles.css
Labels: pass

#193 waid00-cv05
  www/waid00/cv04/dynamic/register.php
  www/waid00/cv05/orders/records.txt
  www/waid00/cv05/products/records.txt
  www/waid00/cv05/users/records.txt
  www/waid00/cv05XAMPP/Abstract/Database.php
  www/waid00/cv05XAMPP/Classes/OrdersDB.php
  www/waid00/cv05XAMPP/Classes/ProductsDB.php
  www/waid00/cv05XAMPP/Classes/UsersDB.php
  www/waid00/cv05XAMPP/Interface/DatabaseOperations.php
  www/waid00/cv05XAMPP/index.php
  www/waid00/cv05XAMPP/orders/records.txt
  www/waid00/cv05XAMPP/products/records.txt
  www/waid00/cv05XAMPP/users/records.txt
  www/waid00/cv05eso/Abstract/Database.php
  www/waid00/cv05eso/Classes/OrdersDB.php
  www/waid00/cv05eso/Classes/ProductsDB.php
  www/waid00/cv05eso/Classes/UsersDB.php
  www/waid00/cv05eso/Interface/DatabaseOperations.php
  www/waid00/cv05eso/index.php
  www/waid00/cv05eso/orders/records.txt
  www/waid00/cv05eso/products/records.txt
  www/waid00/cv05eso/users/records.txt
  www/waid00/cv05esotemp/index.php
  www/waid00/cv05esotemp/orders/records.txt
  www/waid00/cv05esotemp/products/records.txt
  www/waid00/cv05esotemp/users/records.txt
Labels: pass, needs fixing

#204 bukp00-cv06
  www/bukp00/cv06/components/footer.php
  www/bukp00/cv06/components/header.php
  www/bukp00/cv06/components/product-list.php
  www/bukp00/cv06/config.php
  www/bukp00/cv06/css/bootstrap.css
  www/bukp00/cv06/css/main.css
  www/bukp00/cv06/database/CategoriesDatabase.php
  www/bukp00/cv06/database/Database.php
  www/bukp00/cv06/database/ProductsDatabase.php
  www/bukp00/cv06/index.php
  www/bukp00/cv06/utils.php
Labels: pass

#207 baia04-cv06
  www/baia04/cv06/config.php
  www/baia04/cv06/db/CategoriesDB.php
  www/baia04/cv06/db/Database.php
  www/baia04/cv06/db/DatabaseInterface.php
  www/baia04/cv06/db/DiscountsDB.php
  www/baia04/cv06/db/ProductsDB.php
  www/baia04/cv06/img/Star_0.svg
  www/baia04/cv06/img/Star_1.svg
  www/baia04/cv06/img/leaves.png
  www/baia04/cv06/img/logo.png
  www/baia04/cv06/img/product1.png
  www/baia04/cv06/img/product2.png
  www/baia04/cv06/img/product3.png
  www/baia04/cv06/img/product4.png
  www/baia04/cv06/img/product5.png
  www/baia04/cv06/img/product6.png
  www/baia04/cv06/img/tea_cup.png
  www/baia04/cv06/img/tea_cup2.png
  www/baia04/cv06/img/tea_cup3.png
  www/baia04/cv06/index.php
  www/baia04/cv06/src/body.php
  www/baia04/cv06/src/header.php
  www/baia04/cv06/styles/style.css
Labels: pass

#208 vlcj07-cv06
  www/vlcj07/cv06/app/CategoryDisplay.php
  www/vlcj07/cv06/app/ProductDisplay.php
  www/vlcj07/cv06/app/SlideDisplay.php
  www/vlcj07/cv06/app/footer.php
  www/vlcj07/cv06/app/header.php
  www/vlcj07/cv06/css/input.css
  www/vlcj07/cv06/css/styles.css
  www/vlcj07/cv06/database/CategoriesDB.php
  www/vlcj07/cv06/database/DB.php
  www/vlcj07/cv06/database/ProductsDB.php
  www/vlcj07/cv06/database/SlidesDB.php
  www/vlcj07/cv06/database/config.php
  www/vlcj07/cv06/index.php
  www/vlcj07/cv06/js/main.js
  www/vlcj07/cv06/package-lock.json
  www/vlcj07/cv06/package.json
  www/vlcj07/cv06/tailwind.config.js
Labels: pass

#210 janl22-cv06
  www/janl22/cv06/assets/css/main.css
  www/janl22/cv06/assets/css/stylesBootstrap.css
  www/janl22/cv06/assets/img/favicon.ico
  www/janl22/cv06/classes/CategoriesDB.php
  www/janl22/cv06/classes/Database.php
  www/janl22/cv06/classes/ProductsDB.php
  www/janl22/cv06/classes/SlidesDB.php
  www/janl22/cv06/components/navigation.php
  www/janl22/cv06/components/productDisplay.php
  www/janl22/cv06/components/slidesDisplay.php
  www/janl22/cv06/config/database.php
  www/janl22/cv06/index.php
  www/janl22/cv06/templates/footer.php
  www/janl22/cv06/templates/header.php
Labels: pass

#209 bigc00-cv02
  www/bigc00/cv02/Person.php
  www/bigc00/cv02/cards.php
  www/bigc00/cv02/header.php
  www/bigc00/cv02/img/avatar.jpeg
  www/bigc00/cv02/index.php
  www/bigc00/cv02/styles/style.css
  www/bigc00/cv02/utils.php
Labels: pass, late PR

#212 tynk00-cv06
  www/tynk00/cv06/database/categoriesDB.php
  www/tynk00/cv06/database/database.php
  www/tynk00/cv06/database/databaseConfig.php
  www/tynk00/cv06/database/databaseConnection.php
  www/tynk00/cv06/database/productsDB.php
  www/tynk00/cv06/error.png
  www/tynk00/cv06/footer.php
  www/tynk00/cv06/header.php
  www/tynk00/cv06/icon.png
  www/tynk00/cv06/index.php
  www/tynk00/cv06/logo.png
  www/tynk00/cv06/navbar.php
  www/tynk00/cv06/offers.php
  www/tynk00/cv06/productCard.php
  www/tynk00/cv06/sidebar.php
Labels: pass

#213 vitd04-cv06
  www/vitd04/cv06/config/db.php
  www/vitd04/cv06/dist/assets/favicon.ico
  www/vitd04/cv06/dist/css/styles.css
  www/vitd04/cv06/dist/js/scripts.js
  www/vitd04/cv06/fiveserver.config.js
  www/vitd04/cv06/index.php
  www/vitd04/cv06/input.css
  www/vitd04/cv06/lib/database.php
  www/vitd04/cv06/package-lock.json
  www/vitd04/cv06/package.json
  www/vitd04/cv06/repositories/category_repository.php
  www/vitd04/cv06/repositories/product_repository.php
  www/vitd04/cv06/repositories/slides_repository.php
  www/vitd04/cv06/tailwind.config.js
  www/vitd04/cv06/views/partials/categories_partial.php
  www/vitd04/cv06/views/partials/footer_partial.php
  www/vitd04/cv06/views/partials/header_partial.php
  www/vitd04/cv06/views/partials/product_list_partial.php
  www/vitd04/cv06/views/partials/product_partial.php
  www/vitd04/cv06/views/partials/slider_partial.php
Labels: pass

#214 engt01-cv05
  www/engt01/cv05/Database.php
  www/engt01/cv05/DatabaseOperations.php
  www/engt01/cv05/OrdersDB.php
  www/engt01/cv05/ProductsDB.php
  www/engt01/cv05/UsersDB.php
  www/engt01/cv05/index.php
Labels: pass, late PR

#215 shpd00-cv06
  www/shpd00/cv6/DBConnection.php
  www/shpd00/cv6/Product.php
  www/shpd00/cv6/assets/favicon.ico
  www/shpd00/cv6/css/styles.css
  www/shpd00/cv6/dbconfig.ini
  www/shpd00/cv6/eshop-page-content.php
  www/shpd00/cv6/index.php
  www/shpd00/cv6/templates/footer.php
  www/shpd00/cv6/templates/header.php
  www/shpd00/cv6/templates/html-end.php
  www/shpd00/cv6/templates/html-start.php
  www/shpd00/cv6/templates/navigation.php
  www/shpd00/cv6/templates/page-end.php
  www/shpd00/cv6/templates/page-start.php
Labels: pass

#217 jezf00-cv06
  www/jezf00/cv06/CategoriesDatabase.php
  www/jezf00/cv06/CategoryDisplay.php
  www/jezf00/cv06/Database.php
  www/jezf00/cv06/ProductDisplay.php
  www/jezf00/cv06/ProductsDatabase.php
  www/jezf00/cv06/SliderDisplay.php
  www/jezf00/cv06/SlidesDatabase.php
  www/jezf00/cv06/dbconfig.php
  www/jezf00/cv06/index.php
Labels: pass

#211 bigc00-cv06
  www/bigc00/cv06/config/config.php
  www/bigc00/cv06/css/styles.css
  www/bigc00/cv06/db/CategoriesDB.php
  www/bigc00/cv06/db/Database.php
  www/bigc00/cv06/db/DatabaseOperations.php
  www/bigc00/cv06/db/ProductsDB.php
  www/bigc00/cv06/images/product1.png
  www/bigc00/cv06/images/product2.png
  www/bigc00/cv06/images/product3.png
  www/bigc00/cv06/images/product4.png
  www/bigc00/cv06/includes/card.php
  www/bigc00/cv06/includes/cards.php
  www/bigc00/cv06/includes/categories.php
  www/bigc00/cv06/includes/footer.php
  www/bigc00/cv06/includes/header.php
  www/bigc00/cv06/includes/index.html
  www/bigc00/cv06/includes/slider.php
  www/bigc00/cv06/index.php
Labels: needs fixing

#222 svoi02-cv06
  www/svoi02/cv06/CategoriesDatabase.php
  www/svoi02/cv06/CategoryDisplay.php
  www/svoi02/cv06/Database.php
  www/svoi02/cv06/Navigation.php
  www/svoi02/cv06/ProductDisplay.php
  www/svoi02/cv06/ProductsDatabase.php
  www/svoi02/cv06/SlideDisplay.php
  www/svoi02/cv06/SlidesDatabase.php
  www/svoi02/cv06/config.php
  www/svoi02/cv06/css/styles.css
  www/svoi02/cv06/index.php
Labels: pass

#223 bigc00-cv03
  www/bigc00/cv03/includes/body.php
  www/bigc00/cv03/includes/header.php
  www/bigc00/cv03/index.php
  www/bigc00/cv03/styles/style.css
Labels: pass, late PR

#220 waid00-cv06
  www/waid00/cv06/LICENSE
  www/waid00/cv06/README.md
  www/waid00/cv06/dist/ProductDisplay.php
  www/waid00/cv06/dist/assets/download.jfif
  www/waid00/cv06/dist/assets/favicon.ico
  www/waid00/cv06/dist/css/slider.css
  www/waid00/cv06/dist/css/styles.css
  www/waid00/cv06/dist/database.php
  www/waid00/cv06/dist/eshop_waid00.sql
  www/waid00/cv06/dist/index.php
  www/waid00/cv06/dist/js/scripts.js
  www/waid00/cv06/dist/nav.php
  www/waid00/cv06/package-lock.json
  www/waid00/cv06/package.json
  www/waid00/cv06/scripts/build-assets.js
  www/waid00/cv06/scripts/build-pug.js
  www/waid00/cv06/scripts/build-scripts.js
  www/waid00/cv06/scripts/build-scss.js
  www/waid00/cv06/scripts/clean.js
  www/waid00/cv06/scripts/render-assets.js
  www/waid00/cv06/scripts/render-pug.js
  www/waid00/cv06/scripts/render-scripts.js
  www/waid00/cv06/scripts/render-scss.js
  www/waid00/cv06/scripts/sb-watch.js
  www/waid00/cv06/scripts/start-debug.js
  www/waid00/cv06/scripts/start.js
  www/waid00/cv06/src/assets/favicon.ico
  www/waid00/cv06/src/js/scripts.js
  www/waid00/cv06/src/pug/index.pug
  www/waid00/cv06/src/scss/styles.scss
Labels: pass

#218 adaa08-cv06
  www/adaa08/cv06/CategoryDisplay.php
  www/adaa08/cv06/ProductDisplay.php
  www/adaa08/cv06/SlideDisplay.php
  www/adaa08/cv06/assets/favicon.ico
  www/adaa08/cv06/css/styles.css
  www/adaa08/cv06/db/ProductsDB.php
  www/adaa08/cv06/images/drevorubacsky traktor.jpg
  www/adaa08/cv06/images/drevorubacsky-traktor.jpg
  www/adaa08/cv06/images/minitraktor.webp
  www/adaa08/cv06/images/traktor biely.jpeg
  www/adaa08/cv06/images/traktor cerveny.jpg
  www/adaa08/cv06/images/traktor modry.png
  www/adaa08/cv06/images/traktor zeleny.avif
  www/adaa08/cv06/images/traktor zlty.jpeg
  www/adaa08/cv06/images/traktor-biely.jpeg
  www/adaa08/cv06/images/traktor-cerveny.jpg
  www/adaa08/cv06/images/traktor-modry.png
  www/adaa08/cv06/images/traktor-zeleny.avif
  www/adaa08/cv06/images/traktor-zlty.jpeg
  www/adaa08/cv06/index.php
  www/adaa08/cv06/js/db/ProductsDB.php
  www/adaa08/cv06/js/scripts.js
Labels: pass

#224 bigc00-cv04
  www/bigc00/cv04/admin/users.php
  www/bigc00/cv04/config/config.php
  www/bigc00/cv04/database/users.db
  www/bigc00/cv04/includes/header.php
  www/bigc00/cv04/includes/loginBody.php
  www/bigc00/cv04/includes/main.php
  www/bigc00/cv04/includes/registrationBody.php
  www/bigc00/cv04/index.php
  www/bigc00/cv04/login.php
  www/bigc00/cv04/registration.php
  www/bigc00/cv04/styles/style.css
  www/bigc00/cv04/utils.php
Labels: pass, late PR

#235 bigc00-cv05
  www/bigc00/cv05/database/database.php
  www/bigc00/cv05/index.php
Labels: pass, late PR

#225 janl22-cv09
  www/janl22/cv09/assets/css/main.css
  www/janl22/cv09/assets/css/stylesBootstrap.css
  www/janl22/cv09/assets/img/favicon.ico
  www/janl22/cv09/classes/CategoriesDB.php
  www/janl22/cv09/classes/Database.php
  www/janl22/cv09/classes/ProductsDB.php
  www/janl22/cv09/classes/SlidesDB.php
  www/janl22/cv09/classes/StatusMessage.php
  www/janl22/cv09/classes/User.php
  www/janl22/cv09/classes/UsersDB.php
  www/janl22/cv09/components/cart/add.php
  www/janl22/cv09/components/cart/index.php
  www/janl22/cv09/components/cart/remove.php
  www/janl22/cv09/components/homepage/index.php
  www/janl22/cv09/components/homepage/slides.php
  www/janl22/cv09/components/product/delete.php
  www/janl22/cv09/components/product/edit.php
  www/janl22/cv09/components/product/index.php
  www/janl22/cv09/components/user/functions.php
  www/janl22/cv09/components/user/login.php
  www/janl22/cv09/components/user/logout.php
  www/janl22/cv09/components/user/profile.php
  www/janl22/cv09/components/user/registration.php
  www/janl22/cv09/composer.json
  www/janl22/cv09/composer.lock
  www/janl22/cv09/config/app.php
  www/janl22/cv09/config/database.php
  www/janl22/cv09/config/server.php
  www/janl22/cv09/index.php
  www/janl22/cv09/router.php
  www/janl22/cv09/templates/400.php
  www/janl22/cv09/templates/404.php
  www/janl22/cv09/templates/footer.php
  www/janl22/cv09/templates/header.php
  www/janl22/cv09/templates/navigation.php
  www/janl22/cv09/utils/functions.php
  www/janl22/cv09/vendor/autoload.php
  www/janl22/cv09/vendor/composer/ClassLoader.php
  www/janl22/cv09/vendor/composer/InstalledVersions.php
  www/janl22/cv09/vendor/composer/LICENSE
  www/janl22/cv09/vendor/composer/autoload_classmap.php
  www/janl22/cv09/vendor/composer/autoload_namespaces.php
  www/janl22/cv09/vendor/composer/autoload_psr4.php
  www/janl22/cv09/vendor/composer/autoload_real.php
  www/janl22/cv09/vendor/composer/autoload_static.php
  www/janl22/cv09/vendor/composer/installed.json
  www/janl22/cv09/vendor/composer/installed.php
  www/janl22/cv09/vendor/composer/platform_check.php
  www/janl22/cv09/vendor/firebase/php-jwt/CHANGELOG.md
  www/janl22/cv09/vendor/firebase/php-jwt/LICENSE
  www/janl22/cv09/vendor/firebase/php-jwt/README.md
  www/janl22/cv09/vendor/firebase/php-jwt/composer.json
  www/janl22/cv09/vendor/firebase/php-jwt/src/BeforeValidException.php
  www/janl22/cv09/vendor/firebase/php-jwt/src/CachedKeySet.php
  www/janl22/cv09/vendor/firebase/php-jwt/src/ExpiredException.php
  www/janl22/cv09/vendor/firebase/php-jwt/src/JWK.php
  www/janl22/cv09/vendor/firebase/php-jwt/src/JWT.php
  www/janl22/cv09/vendor/firebase/php-jwt/src/Key.php
  www/janl22/cv09/vendor/firebase/php-jwt/src/SignatureInvalidException.php
Labels: pass

#226 birs03-cv09
  www/birs03/cv09/Database.php
  www/birs03/cv09/ProductsDatabase.php
  www/birs03/cv09/add.php
  www/birs03/cv09/addForm.php
  www/birs03/cv09/assets/favicon.ico
  www/birs03/cv09/buy.php
  www/birs03/cv09/cart.php
  www/birs03/cv09/config.php
  www/birs03/cv09/css/styles.css
  www/birs03/cv09/delete.php
  www/birs03/cv09/edit.php
  www/birs03/cv09/editForm.php
  www/birs03/cv09/footer.php
  www/birs03/cv09/header.php
  www/birs03/cv09/index.php
  www/birs03/cv09/injection.php
  www/birs03/cv09/js/scripts.js
  www/birs03/cv09/login.php
  www/birs03/cv09/logout.php
  www/birs03/cv09/pagination.php
  www/birs03/cv09/profile.php
  www/birs03/cv09/remove.php
Labels: approved

#229 vikd00-cv09
  www/vikd00/cv09/buy.php
  www/vikd00/cv09/cart.php
  www/vikd00/cv09/create-item.php
  www/vikd00/cv09/dbconfig.php
  www/vikd00/cv09/delete-item.php
  www/vikd00/cv09/edit-item.php
  www/vikd00/cv09/footer.php
  www/vikd00/cv09/header.php
  www/vikd00/cv09/index.php
  www/vikd00/cv09/login.php
  www/vikd00/cv09/logout.php
  www/vikd00/cv09/navbar.php
  www/vikd00/cv09/pagination.php
  www/vikd00/cv09/profile.php
  www/vikd00/cv09/remove-item.php
  www/vikd00/cv09/styles.css
Labels: approved

#238 mikd08-cv09
  www/mikd08/cv9/buy.php
  www/mikd08/cv9/cart.php
  www/mikd08/cv9/create.php
  www/mikd08/cv9/db.php
  www/mikd08/cv9/delete.php
  www/mikd08/cv9/edit.php
  www/mikd08/cv9/footer.php
  www/mikd08/cv9/header.php
  www/mikd08/cv9/index.php
  www/mikd08/cv9/login.php
  www/mikd08/cv9/logout.php
  www/mikd08/cv9/remove.php
  www/mikd08/sp/admin.php
  www/mikd08/sp/cart.php
  www/mikd08/sp/index.php
  www/mikd08/sp/logIn.php
  www/mikd08/sp/logged.php
  www/mikd08/sp/profile.php
  www/mikd08/sp/register.php
Labels: pass

#240 tynk00-cv09
  www/tynk00/cv09/cartModel.php
  www/tynk00/cv09/components/footer.php
  www/tynk00/cv09/components/header.php
  www/tynk00/cv09/components/navbar.php
  www/tynk00/cv09/components/offers.php
  www/tynk00/cv09/components/pagination.php
  www/tynk00/cv09/components/productCard.php
  www/tynk00/cv09/components/sidebar.php
  www/tynk00/cv09/css/style.css
  www/tynk00/cv09/database/categoriesDB.php
  www/tynk00/cv09/database/database.php
  www/tynk00/cv09/database/databaseConfig.php
  www/tynk00/cv09/database/databaseConnection.php
  www/tynk00/cv09/database/loadData.php
  www/tynk00/cv09/database/productsDB.php
  www/tynk00/cv09/database/usersDB.php
  www/tynk00/cv09/img/avatar-placeholder.jpeg
  www/tynk00/cv09/img/error.png
  www/tynk00/cv09/img/icon.png
  www/tynk00/cv09/img/logo.png
  www/tynk00/cv09/index.php
  www/tynk00/cv09/js/index.js
  www/tynk00/cv09/loader.php
  www/tynk00/cv09/login.php
  www/tynk00/cv09/pages/cart.php
  www/tynk00/cv09/pages/deleteProduct.php
  www/tynk00/cv09/pages/home.php
  www/tynk00/cv09/pages/insertProduct.php
  www/tynk00/cv09/pages/login.php
  www/tynk00/cv09/pages/logout.php
  www/tynk00/cv09/pages/product.php
  www/tynk00/cv09/pages/productEditor.php
  www/tynk00/cv09/pages/productManager.php
  www/tynk00/cv09/pages/profile.php
  www/tynk00/cv09/pages/register.php
  www/tynk00/cv09/pages/users.php
Labels: pass

#241 smap01-cv09
  www/smap01/cv09/buy.php
  www/smap01/cv09/cart.php
  www/smap01/cv09/config.php
  www/smap01/cv09/create-item.php
  www/smap01/cv09/database.php
  www/smap01/cv09/delete-item.php
  www/smap01/cv09/edit-item.php
  www/smap01/cv09/incl/footer.php
  www/smap01/cv09/incl/header.php
  www/smap01/cv09/index.php
  www/smap01/cv09/login.php
  www/smap01/cv09/logout.php
  www/smap01/cv09/profile.php
  www/smap01/cv09/remove-item.php
Labels: pass

#243 engt01-cv09
  www/engt01/cv09/.gitignore
  www/engt01/cv09/buy.php
  www/engt01/cv09/cart.php
  www/engt01/cv09/components/footer.php
  www/engt01/cv09/components/header.php
  www/engt01/cv09/create-item.php
  www/engt01/cv09/css/styles.css
  www/engt01/cv09/db/Database.php
  www/engt01/cv09/db/ProductsDatabase.php
  www/engt01/cv09/delete-item.php
  www/engt01/cv09/edit-item.php
  www/engt01/cv09/index.php
  www/engt01/cv09/login.php
  www/engt01/cv09/logout.php
  www/engt01/cv09/remove-item.php
Labels: pass

#245 pank09-cv09
  www/pank09/cv09/assets/styles.css
  www/pank09/cv09/cart-add-to.php
  www/pank09/cv09/cart-remove-from.php
  www/pank09/cv09/cart.php
  www/pank09/cv09/classes/AbstractClasses/AbstractDatabase.php
  www/pank09/cv09/classes/Interfaces/InterfaceDatabaseOperations.php
  www/pank09/cv09/classes/ProductsDB.php
  www/pank09/cv09/components/base/foot.php
  www/pank09/cv09/components/base/head.php
  www/pank09/cv09/components/base/nav.php
  www/pank09/cv09/components/cart-items.php
  www/pank09/cv09/components/login-form.php
  www/pank09/cv09/components/products.php
  www/pank09/cv09/db/config.php
  www/pank09/cv09/index.php
  www/pank09/cv09/item-create.php
  www/pank09/cv09/item-delete.php
  www/pank09/cv09/item-edit.php
  www/pank09/cv09/login.php
  www/pank09/cv09/logout.php
Labels: pass

#246 vlcj07-cv09
  www/vlcj07/cv09/app/ProductDisplayCart.php
  www/vlcj07/cv09/app/ProductDisplayIndex.php
  www/vlcj07/cv09/app/footer.php
  www/vlcj07/cv09/app/header.php
  www/vlcj07/cv09/buy.php
  www/vlcj07/cv09/cart.php
  www/vlcj07/cv09/create-item.php
  www/vlcj07/cv09/css/input.css
  www/vlcj07/cv09/css/styles.css
  www/vlcj07/cv09/db/config.php
  www/vlcj07/cv09/db/db.php
  www/vlcj07/cv09/delete-item.php
  www/vlcj07/cv09/edit-item.php
  www/vlcj07/cv09/index.php
  www/vlcj07/cv09/js/main.js
  www/vlcj07/cv09/login.php
  www/vlcj07/cv09/logout.php
  www/vlcj07/cv09/package-lock.json
  www/vlcj07/cv09/package.json
  www/vlcj07/cv09/profile.php
  www/vlcj07/cv09/remove-item.php
  www/vlcj07/cv09/tailwind.config.js
Labels: pass

#281 vikd00-cv10
  www/vikd00/cv10/auth.php
  www/vikd00/cv10/buy.php
  www/vikd00/cv10/cart.php
  www/vikd00/cv10/create-item.php
  www/vikd00/cv10/dbconfig.php
  www/vikd00/cv10/delete-item.php
  www/vikd00/cv10/edit-item.php
  www/vikd00/cv10/footer.php
  www/vikd00/cv10/header.php
  www/vikd00/cv10/index.php
  www/vikd00/cv10/login.php
  www/vikd00/cv10/logout.php
  www/vikd00/cv10/navbar.php
  www/vikd00/cv10/pagination.php
  www/vikd00/cv10/profile.php
  www/vikd00/cv10/register.php
  www/vikd00/cv10/remove-item.php
  www/vikd00/cv10/styles.css
  www/vikd00/cv10/update-privilege.php
  www/vikd00/cv10/users.php
  www/vikd00/cv10/world-clock.php
Labels: pass

#191 jezf00-cv05
  www/jezf00/cv05/database/DatabaseOperations.php
  www/jezf00/cv05/database/OrdersDB.php
  www/jezf00/cv05/database/ProductsDB.php
  www/jezf00/cv05/database/UsersDB.php
  www/jezf00/cv05/database/database.php
  www/jezf00/cv05/db-storage/OrdersDB.db
  www/jezf00/cv05/db-storage/ProductsDB.db
  www/jezf00/cv05/db-storage/UsersDB.db
  www/jezf00/cv05/index.php
Labels: pass

#288 vejm04-cv05
  www/vejm04/cv05/classes/OrdersDB.php
  www/vejm04/cv05/classes/ProductsDB.php
  www/vejm04/cv05/classes/UsersDB.php
  www/vejm04/cv05/classes/abstract/AbstractDatabase.php
  www/vejm04/cv05/classes/interfaces/InterfaceDatabaseOperations.php
  www/vejm04/cv05/index.php
  www/vejm04/cv05/pdo.php
  www/vejm04/cv05/test.php
Labels: pass, late PR

#284 vlcj07-cv10
  www/vlcj07/cv10/app/ClockDisplay.php
  www/vlcj07/cv10/app/ProductDisplayCart.php
  www/vlcj07/cv10/app/ProductDisplayIndex.php
  www/vlcj07/cv10/app/UsersDisplay.php
  www/vlcj07/cv10/app/footer.php
  www/vlcj07/cv10/app/header.php
  www/vlcj07/cv10/authorization.php
  www/vlcj07/cv10/buy.php
  www/vlcj07/cv10/cart.php
  www/vlcj07/cv10/create-item.php
  www/vlcj07/cv10/css/input.css
  www/vlcj07/cv10/css/styles.css
  www/vlcj07/cv10/db/config.php
  www/vlcj07/cv10/db/db.php
  www/vlcj07/cv10/delete-item.php
  www/vlcj07/cv10/edit-item.php
  www/vlcj07/cv10/icons/banana-emoji.png
  www/vlcj07/cv10/index.php
  www/vlcj07/cv10/js/main.js
  www/vlcj07/cv10/login.php
  www/vlcj07/cv10/logout.php
  www/vlcj07/cv10/not-permitted.php
  www/vlcj07/cv10/package-lock.json
  www/vlcj07/cv10/package.json
  www/vlcj07/cv10/profile.php
  www/vlcj07/cv10/registration.php
  www/vlcj07/cv10/remove-item.php
  www/vlcj07/cv10/tailwind.config.js
  www/vlcj07/cv10/users.php
  www/vlcj07/cv10/world-clock.php
Labels: pass

#285 pank09-cv10
  www/pank09/cv10/assets/bootstrap.css
  www/pank09/cv10/assets/images/placeholder.jpg
  www/pank09/cv10/assets/styles.css
  www/pank09/cv10/cart-add-to.php
  www/pank09/cv10/cart-remove-from.php
  www/pank09/cv10/cart.php
  www/pank09/cv10/classes/AbstractClasses/AbstractDatabase.php
  www/pank09/cv10/classes/Interfaces/InterfaceDatabaseOperations.php
  www/pank09/cv10/classes/ProductsDB.php
  www/pank09/cv10/classes/UsersDB.php
  www/pank09/cv10/components/base/foot.php
  www/pank09/cv10/components/base/head.php
  www/pank09/cv10/components/base/nav.php
  www/pank09/cv10/components/cart-items.php
  www/pank09/cv10/components/login-form.php
  www/pank09/cv10/components/products.php
  www/pank09/cv10/components/register-form.php
  www/pank09/cv10/components/user-list.php
  www/pank09/cv10/db/config.php
  www/pank09/cv10/index.php
  www/pank09/cv10/item-create.php
  www/pank09/cv10/item-delete.php
  www/pank09/cv10/item-edit.php
  www/pank09/cv10/login.php
  www/pank09/cv10/logout.php
  www/pank09/cv10/register.php
  www/pank09/cv10/session.php
  www/pank09/cv10/users.php
  www/pank09/cv10/world-clock.php
Labels: pass

#286 smap01-cv10
  www/smap01/cv10/buy.php
  www/smap01/cv10/cart.php
  www/smap01/cv10/config.php
  www/smap01/cv10/create-item.php
  www/smap01/cv10/database.php
  www/smap01/cv10/delete-item.php
  www/smap01/cv10/edit-item.php
  www/smap01/cv10/incl/footer.php
  www/smap01/cv10/incl/header.php
  www/smap01/cv10/index.php
  www/smap01/cv10/login.php
  www/smap01/cv10/logout.php
  www/smap01/cv10/profile.php
  www/smap01/cv10/remove-item.php
  www/smap01/cv10/signup.php
  www/smap01/cv10/users.php
  www/smap01/cv10/world-clock.php
Labels: pass
