Repository nvbach91/4IZ278-2022-2023-LS, pull requests merged in 2023-03, with the labels that each got.

#35 fedp04-cv01
  www/fedp04/cv01/index-card.php
  www/fedp04/cv01/index.php
  www/fedp04/cv01/pepeRound.png
  www/fedp04/cv01/style.css
Labels: needs fixing

#31 kusm02-cv01
  www/kusm02/cv01/business-card.php
  www/kusm02/cv01/css/style.css
  www/kusm02/cv02/Person.php
  www/kusm02/cv02/business-card.php
  www/kusm02/cv02/css/style.css
  www/kusm02/cv02/footer.php
  www/kusm02/cv02/header.php
  www/kusm02/cv02/index.php
Labels: needs fixing

#85 korn03-cv02
  www/korn03/cv02/Person.php
  www/korn03/cv02/css/style.css
  www/korn03/cv02/header.php
  www/korn03/cv02/index.php
Labels: pass

#86 adaa08-cv02
  www/adaa08/cv02/index.php
  www/adaa08/cv02/logo.svg
  www/adaa08/cv02/person.php
  www/adaa08/cv02/style.css
  www/adaa08/cv02/utils.php
Labels: pass

#74 tatv00-cv02
  www/tatv00/cv02/Dockerfile
  www/tatv00/cv02/docker-compose.yml
  www/tatv00/cv02/src/classes/Person.php
  www/tatv00/cv02/src/css/style.css
  www/tatv00/cv02/src/includes/foot.php
  www/tatv00/cv02/src/includes/head.php
  www/tatv00/cv02/src/index.php
Labels: needs fixing

#56 pank09-cv02
  www/pank09/cv02/Student.php
  www/pank09/cv02/array-example.php
  www/pank09/cv02/foot.php
  www/pank09/cv02/head.php
  www/pank09/cv02/index.php
Labels: invalid PR, needs fixing

#91 vlcj07-cv02
  www/vlcj07/cv02/classes/Person.php
  www/vlcj07/cv02/data/data.php
  www/vlcj07/cv02/footer.php
  www/vlcj07/cv02/header.php
  www/vlcj07/cv02/images/Pizza-logo-transparent-PNG.png
  www/vlcj07/cv02/index.php
  www/vlcj07/cv02/styles/style.css
Labels: pass

#92 trad10-cv02
  www/trad10/cv02/BusinessCard.php
  www/trad10/cv02/Person.php
  www/trad10/cv02/css/styles.css
  www/trad10/cv02/footer.php
  www/trad10/cv02/header.php
  www/trad10/cv02/img/verisoft-logo.webp
  www/trad10/cv02/index.php
Labels: pass

#93 vanm34-cv02
  www/vanm34/cv02/css/style.css
  www/vanm34/cv02/head.php
  www/vanm34/cv02/img/background.jpg
  www/vanm34/cv02/img/cat.jpg
  www/vanm34/cv02/img/logo.jpg
  www/vanm34/cv02/img/monke.jpeg
  www/vanm34/cv02/index.php
  www/vanm34/cv02/person.php
Labels: pass

#41 vejm04-cv01
  www/vejm04/cv01/bc.php
  www/vejm04/cv01/img/icon.png
  www/vejm04/cv01/index.php
  www/vejm04/cv01/style.css
Labels: pass, needs fixing

#81 macz02-cv02
  www/macz02/cv02/Person.php
  www/macz02/cv02/avatar.jpg
  www/macz02/cv02/avatar2.jpg
  www/macz02/cv02/avatar3.jpg
  www/macz02/cv02/foot.php
  www/macz02/cv02/head.php
  www/macz02/cv02/index.php
  www/macz02/cv02/styles.css
Labels: needs fixing

#40 smap01-cv01
  www/smap01/cv01/css/stylesheet.css
  www/smap01/cv01/img/image-background.jpg
  www/smap01/cv01/img/logo_company.png
  www/smap01/cv01/img/user_avatar.png
  www/smap01/cv01/index.php
Labels: pass, needs fixing

#90 mikd08-cv02
  www/mikd08/cv1/logo.jpg
  www/mikd08/cv1/vizitka.css
  www/mikd08/cv1/vizitka.php
  www/mikd08/cv2/Person.php
  www/mikd08/cv2/head.php
  www/mikd08/cv2/index.php
  www/mikd08/cv2/logo.jpg
  www/mikd08/cv2/potato.png
  www/mikd08/cv2/vizitka.php
  www/mikd08/cv2/vizitka2.css
Labels: pass, needs fixing

#57 tolo00-cv02
  www/tolo00/cv02/avatar.jpg
  www/tolo00/cv02/index.php
  www/tolo00/cv02/model/Company.php
  www/tolo00/cv02/model/Person.php
  www/tolo00/cv02/utils/utils.php
  www/tolo00/cv02/view/BusinessCardBack.php
  www/tolo00/cv02/view/BusinessCardFront.php
  www/tolo00/cv02/view/businessCardBack.php
  www/tolo00/cv02/view/businessCardFront.php
  www/tolo00/cv02/view/businessCards.php
Labels: needs fixing

#95 smap01-cv02
  www/smap01/cv02/classes/Person.php
  www/smap01/cv02/classes/utils.php
  www/smap01/cv02/css/stylesheet.css
  www/smap01/cv02/img/image-background.jpg
  www/smap01/cv02/img/logo_company.png
  www/smap01/cv02/img/user_avatar.png
  www/smap01/cv02/includes/footer.php
  www/smap01/cv02/includes/head.php
  www/smap01/cv02/index.php
Labels: needs fixing

#58 tolo00-cv03
  www/tolo00/cv03/index.php
Labels: pass

#97 baia04-cv03
  www/baia04/cv03/body.php
  www/baia04/cv03/errorsStrings.php
  www/baia04/cv03/header.php
  www/baia04/cv03/img/background.png
  www/baia04/cv03/index.php
  www/baia04/cv03/styles/style.css
  www/baia04/cv03/submitted.php
  www/baia04/cv03/utils.php
Labels: pass

#98 cham20-cv03
  www/cham20/cv03/index.php
  www/cham20/cv03/registration-form.php
Labels: pass

#99 mikd08-cv03
  www/mikd08/cv1/potato.png
  www/mikd08/cv1/vizitka.css
  www/mikd08/cv1/vizitka.php
  www/mikd08/cv3/index.php
  www/mikd08/cv3/registrationForm.php
Labels: pass

#102 bukp00-cv03
  www/bukp00/cv03/css/main.css
  www/bukp00/cv03/footer.php
  www/bukp00/cv03/header.php
  www/bukp00/cv03/index.php
  www/bukp00/cv03/register-form.php
Labels: pass

#104 mudp01-cv03
  www/mudp01/cv03/css/style.css
  www/mudp01/cv03/index.php
Labels: pass

#107 bary01-cv03
  www/bary01/cv03/footer.php
  www/bary01/cv03/header.php
  www/bary01/cv03/index.php
  www/bary01/cv03/registration-form.php
  www/bary01/cv03/styles.css
Labels: pass

#108 tatv00-cv03
  www/tatv00/cv03/classes/Person.php
  www/tatv00/cv03/css/style.css
  www/tatv00/cv03/includes/foot.php
  www/tatv00/cv03/includes/head.php
  www/tatv00/cv03/index.php
  www/tatv00/cv03/register-form.php
Labels: pass

#109 birs03-cv03
  www/birs03/cv03/foot.php
  www/birs03/cv03/get-user.php
  www/birs03/cv03/head.php
  www/birs03/cv03/index.php
  www/birs03/cv03/registration-form.php
  www/birs03/cv03/style.css
Labels: pass

#110 pank09-cv03
  www/pank09/cv03/assets/images/colored.jpg
  www/pank09/cv03/assets/style.css
  www/pank09/cv03/index.php
  www/pank09/cv03/registration-form.php
Labels: pass

#111 jezf00-cv03
  www/jezf00/cv03/includes/footer.php
  www/jezf00/cv03/includes/header.php
  www/jezf00/cv03/index.php
  www/jezf00/cv03/utils.php
Labels: pass

#112 avdn00-cv03
  www/avdn00/cv03/index.php
  www/avdn00/cv03/registration-form.php
  www/avdn00/cv03/style.css
Labels: pass

#113 nezn00-cv03
  www/nezn00/cv3/index.php
  www/nezn00/cv3/registration-form.php
Labels: pass

#114 svoi02-cv03
  www/svoi02/cv03/css/style.css
  www/svoi02/cv03/index.php
Labels: pass

#115 vanm34-cv03
  www/vanm34/cv03/get-users.php
  www/vanm34/cv03/header.php
  www/vanm34/cv03/index.php
  www/vanm34/cv03/register-form.php
  www/vanm34/cv03/style.css
Labels: pass

#117 sucl03-cv03
  www/sucl03/cv03/css/style.css
  www/sucl03/cv03/index.php
  www/sucl03/cv03/libs/html-footer.php
  www/sucl03/cv03/libs/html-header.php
  www/sucl03/cv03/libs/post-controler.php
  www/sucl03/cv03/libs/send-emails-utf8.php
Labels: pass

#119 vitd04-cv03
  www/vitd04/cv03/fiveserver.config.js
  www/vitd04/cv03/index.php
  www/vitd04/cv03/input.css
  www/vitd04/cv03/output.css
  www/vitd04/cv03/package-lock.json
  www/vitd04/cv03/package.json
  www/vitd04/cv03/partials/footer.php
  www/vitd04/cv03/partials/header.php
  www/vitd04/cv03/tailwind.config.js
Labels: pass

#120 lasj06-cv03
  www/lasj06/cv03/css/style.css
  www/lasj06/cv03/foot.php
  www/lasj06/cv03/head.php
  www/lasj06/cv03/index.php
Labels: pass

#121 tynk00-cv03
  www/tynk00/cv03/index.php
  www/tynk00/cv03/validation.php
Labels: pass

#122 kusm02-cv03
  www/kusm02/cv01/business-card.php
  www/kusm02/cv02/Person.php
  www/kusm02/cv02/business-card_02.php
  www/kusm02/cv03/css/style.css
  www/kusm02/cv03/img/keanu.jpg
  www/kusm02/cv03/includes/footer.php
  www/kusm02/cv03/includes/header.php
  www/kusm02/cv03/index.php
  www/kusm02/cv03/utils.php
Labels: pass

#94 shpd00-cv02
  www/shpd00/cv02/css/styles.css
  www/shpd00/cv02/img/croc.svg
  www/shpd00/cv02/img/galaxy.svg
  www/shpd00/cv02/img/jedi-logo.svg
  www/shpd00/cv02/index.php
  www/shpd00/cv02/person-cards.php
  www/shpd00/cv02/person.php
  www/shpd00/cv02/templates/html-end.php
  www/shpd00/cv02/templates/html-start.php
  www/shpd00/cv02/utils.php
Labels: needs fixing, approved

#125 fedp04-cv03
  www/fedp04/cv03/index.php
  www/fedp04/cv03/registration-form.php
  www/fedp04/cv03/style.css
Labels: pass

#127 engt01-cv03
  www/engt01/cv03/footer.php
  www/engt01/cv03/header.php
  www/engt01/cv03/index.php
Labels: pass

#128 dalp01-cv03
  www/dalp01/cv03/css/style.css
  www/dalp01/cv03/includes/head.php
  www/dalp01/cv03/includes/registration-form.php
  www/dalp01/cv03/index.php
Labels: pass

#129 chet01-cv3
  www/chet01/cv03/Person.php
  www/chet01/cv03/cards.php
  www/chet01/cv03/index.php
  www/chet01/cv03/style.css
Labels: pass

#131 vejm04-cv03
  www/vejm04/cv03/index.php
  www/vejm04/cv03/registration_form.php
  www/vejm04/cv03/style.css
Labels: approved

#132 smap01-cv03
  www/smap01/cv03/css/styles.css
  www/smap01/cv03/includes/footer.php
  www/smap01/cv03/includes/header.php
  www/smap01/cv03/index.php
  www/smap01/cv03/validation.php
Labels: pass

#59 tolo00-cv04
  www/tolo00/cv04/admin/users.php
  www/tolo00/cv04/functions.php
  www/tolo00/cv04/login.php
  www/tolo00/cv04/register.php
  www/tolo00/cv04/users.db
Labels: invalid PR, pass, needs fixing, pending

#134 cham20-cv04
  www/cham20/cv04/admin/users.php
  www/cham20/cv04/database.db
  www/cham20/cv04/footer.php
  www/cham20/cv04/header.php
  www/cham20/cv04/index.php
  www/cham20/cv04/logged.php
  www/cham20/cv04/login.php
  www/cham20/cv04/main.css
  www/cham20/cv04/registration-form.php
  www/cham20/cv04/utils.php
Labels: pass

#137 vikd00-cv04
  www/vikd00/cv04/admin/users.php
  www/vikd00/cv04/index.php
  www/vikd00/cv04/login.php
  www/vikd00/cv04/registration.php
  www/vikd00/cv04/src/foot.php
  www/vikd00/cv04/src/head.php
  www/vikd00/cv04/style.css
  www/vikd00/cv04/users.db
  www/vikd00/cv04/utils.php
Labels: pass

#140 voll03-cv04
  www/voll03/cv04/admin/users.php
  www/voll03/cv04/css/input.css
  www/voll03/cv04/css/output.css
  www/voll03/cv04/db/DatabaseService.php
  www/voll03/cv04/db/database.db
  www/voll03/cv04/error-panel.php
  www/voll03/cv04/footer.php
  www/voll03/cv04/getback.php
  www/voll03/cv04/head.php
  www/voll03/cv04/index.php
  www/voll03/cv04/login.php
  www/voll03/cv04/package-lock.json
  www/voll03/cv04/package.json
  www/voll03/cv04/register.php
  www/voll03/cv04/tailwind.config.js
  www/voll03/cv04/utils.php
  www/voll03/cv04/validation.php
Labels: pass

#141 bukp00-cv04
  www/bukp00/cv04/css/main.css
  www/bukp00/cv04/database.db
  www/bukp00/cv04/footer.php
  www/bukp00/cv04/header.php
  www/bukp00/cv04/index.php
  www/bukp00/cv04/login.php
  www/bukp00/cv04/register.php
  www/bukp00/cv04/users.php
  www/bukp00/cv04/utils.php
Labels: pass

#142 bary01-cv04
  www/bary01/cv04/footer.php
  www/bary01/cv04/header.php
  www/bary01/cv04/index.php
  www/bary01/cv04/login.php
  www/bary01/cv04/registration-form.php
  www/bary01/cv04/styles.css
  www/bary01/cv04/users.db
  www/bary01/cv04/users.php
  www/bary01/cv04/utils.php
Labels: pass

#144 tatv00-cv04
  www/tatv00/cv04/classes/Person.php
  www/tatv00/cv04/css/style.css
  www/tatv00/cv04/database.db
  www/tatv00/cv04/includes/foot.php
  www/tatv00/cv04/includes/head.php
  www/tatv00/cv04/index.php
  www/tatv00/cv04/login.php
  www/tatv00/cv04/register-form.php
  www/tatv00/cv04/users.php
  www/tatv00/cv04/utils.php
Labels: pass

#143 dalp01-cv04
  www/dalp01/cv04/css/style.css
  www/dalp01/cv04/includes/head.php
  www/dalp01/cv04/includes/registration-form.php
  www/dalp01/cv04/includes/utils.php
  www/dalp01/cv04/index.php
  www/dalp01/cv04/login.php
  www/dalp01/cv04/users.db
  www/dalp01/cv04/users.php
Labels: pass, needs fixing

#146 birs03-cv04
  www/birs03/cv04/admin/users.php
  www/birs03/cv04/foot.php
  www/birs03/cv04/get-user.php
  www/birs03/cv04/head.php
  www/birs03/cv04/home.php
  www/birs03/cv04/index.php
  www/birs03/cv04/login.php
  www/birs03/cv04/registration.php
  www/birs03/cv04/style.css
  www/birs03/cv04/users.db
  www/birs03/cv04/utils.php
Labels: pass

#147 avdn00-cv04
  www/avdn00/cv04/database.db
  www/avdn00/cv04/foot.php
  www/avdn00/cv04/head.php
  www/avdn00/cv04/index.php
  www/avdn00/cv04/login.php
  www/avdn00/cv04/registration.php
  www/avdn00/cv04/style.css
  www/avdn00/cv04/utils.php
Labels: pass

#148 vanm34-cv04
  www/vanm34/cv04/css/card_style.css
  www/vanm34/cv04/css/style.css
  www/vanm34/cv04/get-users.php
  www/vanm34/cv04/header.php
  www/vanm34/cv04/img/background.jpg
  www/vanm34/cv04/index.php
  www/vanm34/cv04/loggedUsers.php
  www/vanm34/cv04/login.php
  www/vanm34/cv04/register-form.php
  www/vanm34/cv04/users.db
  www/vanm34/cv04/utils.php
Labels: pass

#149 kusm02-cv04
  www/kusm02/cv04/Person.php
  www/kusm02/cv04/business-card.php
  www/kusm02/cv04/css/style.css
  www/kusm02/cv04/dashboard.php
  www/kusm02/cv04/database.db
  www/kusm02/cv04/foot.php
  www/kusm02/cv04/footer.php
  www/kusm02/cv04/head.php
  www/kusm02/cv04/header.php
  www/kusm02/cv04/index.php
  www/kusm02/cv04/login.php
  www/kusm02/cv04/registration-form.php
  www/kusm02/cv04/utils.php
Labels: pass

#145 nezn00-cv04
  www/nezn00/cv04/admin/users.php
  www/nezn00/cv04/dtbase.db
  www/nezn00/cv04/footer.php
  www/nezn00/cv04/header.php
  www/nezn00/cv04/index.php
  www/nezn00/cv04/logged_in.php
  www/nezn00/cv04/login.php
  www/nezn00/cv04/registration-form.php
  www/nezn00/cv04/style.css
  www/nezn00/cv04/utils.php
Labels: needs fixing, approved

#150 janl22-cv04
  www/janl22/cv04/assets/css/main.css
  www/janl22/cv04/assets/img/cover.jpg
  www/janl22/cv04/attendees.php
  www/janl22/cv04/classes/StatusMessage.php
  www/janl22/cv04/classes/User.php
  www/janl22/cv04/database/users.d
  www/janl22/cv04/index.php
  www/janl22/cv04/login.php
  www/janl22/cv04/registration.php
  www/janl22/cv04/templates/htmlFooter.php
  www/janl22/cv04/templates/htmlHeader.php
  www/janl22/cv04/utils/config.php
  www/janl22/cv04/utils/functions.php
Labels: pass, needs fixing

#163 trad10-cv03
  www/trad10/cv03/MailSender.php
  www/trad10/cv03/Registration.php
  www/trad10/cv03/footer.php
  www/trad10/cv03/header.php
  www/trad10/cv03/index.php
Labels: approved

#166 kuza13-cv03
  www/kuza13/cv03/index.php
  www/kuza13/cv03/registration-form.php
  www/kuza13/cv03/styles/style.css
Labels: approved

#156 matj28-cv04
  www/matj28/cv02/arrays-example.php
  www/matj28/cv02/classes/Person.php
  www/matj28/cv02/css/stylesheet.css
  www/matj28/cv02/includes/foot.php
  www/matj28/cv02/includes/head.php
  www/matj28/cv02/index.php
  www/matj28/cv02/resources/213841-purple-blank-wave-business-card-background-vector-graphic.jpg
  www/matj28/cv02/resources/DALL·E.png
  www/matj28/cv03/includes/footer.php
  www/matj28/cv03/includes/header.php
  www/matj28/cv03/index.php
  www/matj28/cv03/register-form.php
  www/matj28/cv04/classes/utils.php
  www/matj28/cv04/css/stylesheet.css
  www/matj28/cv04/home-page.php
  www/matj28/cv04/includes/footer.php
  www/matj28/cv04/includes/header.php
  www/matj28/cv04/index.php
  www/matj28/cv04/login.php
  www/matj28/cv04/register-form.php
  www/matj28/cv04/resources/users.db
  www/matj28/cv04/users.php
Labels: approved

#152 lasj06-cv04
  www/lasj06/cv04/admin/users.php
  www/lasj06/cv04/css/style.css
  www/lasj06/cv04/foot.php
  www/lasj06/cv04/head.php
  www/lasj06/cv04/index.php
  www/lasj06/cv04/login.php
  www/lasj06/cv04/users.db
  www/lasj06/cv04/utils.php
Labels: approved

#155 engt01-cv04
  www/engt01/cv04/admin.php
  www/engt01/cv04/footer.php
  www/engt01/cv04/functions.php
  www/engt01/cv04/header.php
  www/engt01/cv04/index.php
  www/engt01/cv04/login.php
  www/engt01/cv04/registration.php
  www/engt01/cv04/users.csv
Labels: pass

#157 fedp04-cv04
  www/fedp04/cv04/database.db
  www/fedp04/cv04/head.php
  www/fedp04/cv04/index.php
  www/fedp04/cv04/login.php
  www/fedp04/cv04/registration-form.php
  www/fedp04/cv04/style.css
  www/fedp04/cv04/tail.php
  www/fedp04/cv04/utils.php
Labels: pass

#158 bubm02-cv04
  www/bubm02/cv04/User.php
  www/bubm02/cv04/dashboard.php
  www/bubm02/cv04/database.db
  www/bubm02/cv04/foot.php
  www/bubm02/cv04/head.php
  www/bubm02/cv04/index.php
  www/bubm02/cv04/login.php
  www/bubm02/cv04/registration.php
  www/bubm02/cv04/style.css
  www/bubm02/cv04/utils.php
Labels: pass

#159 jezf00-cv04
  www/jezf00/cv04/admin/users.php
  www/jezf00/cv04/css/style.css
  www/jezf00/cv04/database/users.db
  www/jezf00/cv04/img/background6.jpg
  www/jezf00/cv04/incl/footer.php
  www/jezf00/cv04/incl/header.php
  www/jezf00/cv04/index.php
  www/jezf00/cv04/login.php
  www/jezf00/cv04/registration.php
  www/jezf00/cv04/utils/utils.php
Labels: pass

#160 vlcj07-cv04
  www/vlcj07/cv04/admin/users.php
  www/vlcj07/cv04/css/input.css
  www/vlcj07/cv04/css/style.css
  www/vlcj07/cv04/db/users.db
  www/vlcj07/cv04/images/vector-illustration-cool-detailed-red-260nw-94498447.jpg.webp
  www/vlcj07/cv04/images/web.png
  www/vlcj07/cv04/index.php
  www/vlcj07/cv04/php/footer.php
  www/vlcj07/cv04/php/header.php
  www/vlcj07/cv04/php/home.php
  www/vlcj07/cv04/php/login-form.php
  www/vlcj07/cv04/php/login.php
  www/vlcj07/cv04/php/registration-form.php
  www/vlcj07/cv04/php/registration.php
  www/vlcj07/cv04/php/utils.php
  www/vlcj07/cv04/tailwind.config.js
Labels: pass

#162 sucl03-cv04
  www/sucl03/cv04/admin/users.php
  www/sucl03/cv04/config/read-dotenv.php
  www/sucl03/cv04/controllers/login.php
  www/sucl03/cv04/controllers/registration.php
  www/sucl03/cv04/css/style.css
  www/sucl03/cv04/database/users.db
  www/sucl03/cv04/index.php
  www/sucl03/cv04/libs/html-footer.php
  www/sucl03/cv04/libs/html-header.php
  www/sucl03/cv04/libs/init.php
  www/sucl03/cv04/libs/send-emails-utf8.php
  www/sucl03/cv04/libs/utils.php
  www/sucl03/cv04/login.php
  www/sucl03/cv04/models/users.php
  www/sucl03/cv04/registration.php
Labels: pass

#164 trad10-cv04
  www/trad10/cv04/footer.php
  www/trad10/cv04/header.php
  www/trad10/cv04/index.php
  www/trad10/cv04/login.php
  www/trad10/cv04/profile.php
  www/trad10/cv04/registration.php
  www/trad10/cv04/users.db
  www/trad10/cv04/users.php
  www/trad10/cv04/utils.php
Labels: pass

#168 mudp01 - cv04
  www/mudp01/cv04/admin/users.php
  www/mudp01/cv04/form/css/style.css
  www/mudp01/cv04/form/index.php
  www/mudp01/cv04/form/login.php
  www/mudp01/cv04/index.php
  www/mudp01/cv04/users.db
Labels: pass

#60 tolo00-cv05
  www/tolo00/cv05/db/ProductsDB.db
  www/tolo00/cv05/db/UsersDB.db
  www/tolo00/cv05/index.php
Labels: pass

#170 baia04-cv05
  www/baia04/cv05/Database.php
  www/baia04/cv05/DatabaseOperations.php
  www/baia04/cv05/StringBuilder.php
  www/baia04/cv05/index.php
  www/baia04/cv05/oopdatabase.php
  www/baia04/cv05/src/header.php
  www/baia04/cv05/src/technique.php
  www/baia04/cv05/src/techniqueDiv.php
  www/baia04/cv05/styles/style.css
Labels: pass

#171 voll03-cv05
  www/voll03/cv05/app/Database.php
  www/voll03/cv05/app/DatabaseOperations.php
  www/voll03/cv05/app/OrdersDB.php
  www/voll03/cv05/app/ProductsDB.php
  www/voll03/cv05/app/UsersDB.php
  www/voll03/cv05/db/orders.db
  www/voll03/cv05/db/products.db
  www/voll03/cv05/db/users.db
  www/voll03/cv05/footer.php
  www/voll03/cv05/head.php
  www/voll03/cv05/index.php
  www/voll03/cv05/test.php
Labels: pass

#172 vikd00-cv05
  www/vikd00/cv05/database-operations.php
  www/vikd00/cv05/database.php
  www/vikd00/cv05/index.php
  www/vikd00/cv05/ordersDb.php
  www/vikd00/cv05/productsDb.php
  www/vikd00/cv05/usersDb.php
Labels: pass

#175 bukp00-cv05
  www/bukp00/cv05/css/main.css
  www/bukp00/cv05/database/database.php
  www/bukp00/cv05/db-store/OrdersDB.db
  www/bukp00/cv05/db-store/ProductsDB.db
  www/bukp00/cv05/db-store/UsersDB.db
  www/bukp00/cv05/footer.php
  www/bukp00/cv05/header.php
  www/bukp00/cv05/index.php
Labels: pass

#176 tatv00-cv05
  www/tatv00/cv05/db.php
  www/tatv00/cv05/includes/foot.php
  www/tatv00/cv05/includes/head.php
  www/tatv00/cv05/index.php
Labels: pass

#177 mikd08-cv05
  www/mikd08/cv4/funcs.php
  www/mikd08/cv4/index.php
  www/mikd08/cv4/login.php
  www/mikd08/cv4/regForm.php
  www/mikd08/cv4/users.db
  www/mikd08/cv5/db.php
  www/mikd08/cv5/index.php
Labels: pass

#178 dalp01-cv05
  www/dalp01/cv05/db/orders.db
  www/dalp01/cv05/db/products.db
  www/dalp01/cv05/db/users.db
  www/dalp01/cv05/index.php
Labels: pass

#179 bary01-cv05
  www/bary01/cv05/database/db.php
  www/bary01/cv05/foot.php
  www/bary01/cv05/header.php
  www/bary01/cv05/index.php
Labels: pass

#180 vanm34-cv05
  www/vanm34/cv05/Database.php
  www/vanm34/cv05/DatabaseOperations.php
  www/vanm34/cv05/OrdersDB.php
  www/vanm34/cv05/ProductsDB.php
  www/vanm34/cv05/UsersDB.php
  www/vanm34/cv05/header.php
  www/vanm34/cv05/index.php
Labels: pass

#181 nezn00-cv05
  www/nezn00/cv05/database/orders.db
  www/nezn00/cv05/database/products.db
  www/nezn00/cv05/database/users.db
  www/nezn00/cv05/index.php
Labels: pass

#182 cv05
  www/svoi02/cv05/index.php
Labels: pass

#183 avdn00-cv05
  www/avdn00/cv05/database.php
  www/avdn00/cv05/db/OrdersDB.db
  www/avdn00/cv05/db/ProductsDB.db
  www/avdn00/cv05/db/UsersDB.db
  www/avdn00/cv05/index.php
Labels: pass

#184 janl22-cv05
  www/janl22/cv05/class/Database.php
  www/janl22/cv05/class/OrdersDB.php
  www/janl22/cv05/class/ProductsDB.php
  www/janl22/cv05/class/UsersDB.php
  www/janl22/cv05/database/users.db
  www/janl22/cv05/index.php
  www/janl22/cv05/interface/DatabaseOperations.php
  www/janl22/cv05/template/htmlFooter.php
  www/janl22/cv05/template/htmlHeader.php
Labels: pass

#185 kusm02-cv05
  www/kusm02/cv05/db.php
  www/kusm02/cv05/index.php
  www/kusm02/cv05/ordersdb.php
  www/kusm02/cv05/productsdb.php
  www/kusm02/cv05/userdb.php
Labels: pass

#186 birs03-cv05
  www/birs03/cv05/index.php
  www/birs03/cv05/mysqli.php
  www/birs03/cv05/pdo.php
Labels: pass

#151 korn03-cv04
  www/korn03/cv04/database.db
  www/korn03/cv04/foot.php
  www/korn03/cv04/head.php
  www/korn03/cv04/index.php
  www/korn03/cv04/login.php
  www/korn03/cv04/registration.php
  www/korn03/cv04/users.php
  www/korn03/cv04/utils.php
Labels: pass, needs fixing

#187 macz02 - cv05
  www/macz02/cv05/Database.php
  www/macz02/cv05/DatabaseOperations.php
  www/macz02/cv05/OrdersDB.php
  www/macz02/cv05/ProductsDB.php
  www/macz02/cv05/UsersDB.php
  www/macz02/cv05/index.php
Labels: pass

#188 tynk00-cv05
  www/tynk00/cv05/Icon.png
  www/tynk00/cv05/database.php
  www/tynk00/cv05/db/OrdersDB.db
  www/tynk00/cv05/db/ProductsDB.db
  www/tynk00/cv05/db/UsersDB.db
  www/tynk00/cv05/db/messages.txt
  www/tynk00/cv05/deleteMethod.php
  www/tynk00/cv05/header.php
  www/tynk00/cv05/index.php
  www/tynk00/cv05/messages.txt
  www/tynk00/cv05/navbar.php
  www/tynk00/cv05/orders.php
  www/tynk00/cv05/productForm.php
  www/tynk00/cv05/products.php
  www/tynk00/cv05/setData.php
  www/tynk00/cv05/users.php
Labels: pass

#192 pank09-cv05
  www/pank09/cv05/classes/AbstractClasses/AbstractDatabase.php
  www/pank09/cv05/classes/Interfaces/InterfaceDatabaseOperations.php
  www/pank09/cv05/classes/OrdersDB.php
  www/pank09/cv05/classes/ProductsDB.php
  www/pank09/cv05/classes/UsersDB.php
  www/pank09/cv05/index.php
  www/pank09/cv05/pdo.php
  www/pank09/cv05/test.php
Labels: pass

#198 kuza13-cv05
  www/kuza13/www/kuza13/cv05/Database.php
  www/kuza13/www/kuza13/cv05/DatabaseOperations.php
  www/kuza13/www/kuza13/cv05/OrdersDB.php
  www/kuza13/www/kuza13/cv05/ProductsDB.php
  www/kuza13/www/kuza13/cv05/UsersDB.php
  www/kuza13/www/kuza13/cv05/db/dbUsers.db
  www/kuza13/www/kuza13/cv05/index.php
Labels: pass

#174 bigc00-cv01
  www/bigc00/cv01/img/holka..jpeg
  www/bigc00/cv01/index.php
  www/bigc00/cv01/style/style.css
Labels: pass, late PR
